<?xml version="1.0"?>
<package format="3">
  <name>mio_voice</name>
  <version>0.0.0</version>
  <description>Wake word, STT, local model and TTS glue.</description>
  <maintainer email="rayyan1106adeel@gmail.com">Jalal Ahmed</maintainer>
  <license>TODO</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
